### ISSUE TITLE
Problem playing transcoded audio

### ISSUE THREAD

**Issue by IvanVas** [dough10/PolySonic#64]
# Scenario:

Playing any transcoded song. Works great with mp3
# Observed:

After about 2m of playing there is a long pause (~1m) after which about 20s of music is played. Then the pause again, and so on.
# Logs:
## Client:

`GET http://192.168.0.35:4040/rest/stream.view?u=ivan&v=1.13.0&c=PolySonic&f=json&p=enc%3A6162726163616461627261303938&maxBitRate=320&id=46880 net::ERR_CONTENT_LENGTH_MISMATCH`
### When the pause occurs:

`[2016-02-21 12:53:58,886] INFO InputStreamReaderThread - (/var/subsonic/transcode/ffmpeg) video:0kB audio:4076kB global headers:0kB muxing overhead 0.011429%
[2016-02-21 12:54:00,638] INFO StreamController - Got HTTP range: 3145728-4174172
[2016-02-21 12:54:00,640] INFO PlayQueueInputStream - ivan listening to "Ottmar Liebert - Up Close [FLAC24-96khz]/6-Silence Excerpt.flac"
[2016-02-21 12:54:00,655] INFO TranscodeInputStream - Starting transcoder: [/var/subsonic/transcode/ffmpeg] [-i] [/media/5225f81e-1aa4-410a-ad65-c0761722da69/Nas/Music/Ottmar Liebert - Up Close [FLAC24-96khz]/6-Silence Excerpt.flac] [-map] [0:0] [-b:a] [320k] [-v] [0] [-f] [mp3] [-]
[2016-02-21 12:54:00,867] INFO InputStreamReaderThread - (/var/subsonic/transcode/ffmpeg) Stream mapping:
[2016-02-21 12:54:00,868] INFO InputStreamReaderThread - (/var/subsonic/transcode/ffmpeg)   Stream #0.0 -> #0.0
[2016-02-21 12:54:00,868] INFO InputStreamReaderThread - (/var/subsonic/transcode/ffmpeg) Press ctrl-c to stop encoding
[2016-02-21 12:54:00,869] INFO InputStreamReaderThread - (/var/subsonic/transcode/ffmpeg) Warning, using s16 intermediate sample format for resampling
[2016-02-21 12:54:01,449] INFO InputStreamReaderThread - (/var/subsonic/transcode/ffmpeg) size=      37kB time=1.56 bitrate= 194.4kbits/s
[2016-02-21 12:54:01,953] INFO InputStreamReaderThread - (/var/subsonic/transcode/ffmpeg) size=      67kB time=2.86 bitrate= 193.3kbits/s`
### And a moment after:

`[2016-02-21 12:54:38,167] INFO InputStreamReaderThread - (/var/subsonic/transcode/ffmpeg) size=    3075kB time=131.18 bitrate= 192.0kbits/s
[2016-02-21 12:54:38,441] WARN RESTFilter - Error in REST API: EofException
org.mortbay.jetty.EofException
    at org.mortbay.jetty.HttpGenerator.flush(HttpGenerator.java:760)
    at org.mortbay.jetty.AbstractGenerator$Output.blockForOutput(AbstractGenerator.java:546)
    at org.mortbay.jetty.AbstractGenerator$Output.flush(AbstractGenerator.java:567)
    at org.mortbay.jetty.HttpConnection$Output.flush(HttpConnection.java:907)
    at org.mortbay.jetty.AbstractGenerator$Output.write(AbstractGenerator.java:628)
    at org.mortbay.jetty.AbstractGenerator$Output.write(AbstractGenerator.java:575)
    at net.sourceforge.subsonic.io.RangeOutputStream.write(RangeOutputStream.java:96)
    at net.sourceforge.subsonic.controller.StreamController.handleRequest(StreamController.java:232)
    at net.sourceforge.subsonic.controller.RESTController.stream(RESTController.java:1409)
    at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.springframework.web.servlet.mvc.multiaction.MultiActionController.invokeNamedMethod(MultiActionController.java:473)
    at org.springframework.web.servlet.mvc.multiaction.MultiActionController.handleRequestInternal(MultiActionController.java:410)
    at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
    at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:875)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:807)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:571)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:501)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:487)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1093)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:148)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084)
    at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:265)
    at org.acegisecurity.intercept.web.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:107)
    at org.acegisecurity.intercept.web.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:72)
    at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275)
    at org.acegisecurity.ui.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:166)
    at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275)
    at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
    at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275)
    at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
    at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275)
    at org.acegisecurity.wrapper.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:81)
    at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275)
    at net.sourceforge.subsonic.security.RESTRequestParameterProcessingFilter.doFilter(RESTRequestParameterProcessingFilter.java:113)
    at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275)
    at org.acegisecurity.ui.basicauth.BasicProcessingFilter.doFilter(BasicProcessingFilter.java:173)
    at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275)
    at org.acegisecurity.ui.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
    at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275)
    at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
    at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275)
    at org.acegisecurity.util.FilterChainProxy.doFilter(FilterChainProxy.java:149)
    at org.acegisecurity.util.FilterToBeanProxy.doFilter(FilterToBeanProxy.java:98)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084)
    at net.sourceforge.subsonic.filter.RequestEncodingFilter.doFilter(RequestEncodingFilter.java:43)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084)
    at net.sourceforge.subsonic.filter.RESTFilter.doFilter(RESTFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084)
    at net.sourceforge.subsonic.filter.ParameterDecodingFilter.doFilter(ParameterDecodingFilter.java:54)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084)
    at net.sourceforge.subsonic.filter.BootstrapVerificationFilter.doFilter(BootstrapVerificationFilter.java:59)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:360)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:712)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:405)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:139)
    at org.mortbay.jetty.Server.handle(Server.java:313)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:506)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:830)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:514)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:211)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:381)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:396)
    at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:442)
Caused by: java.io.IOException: Broken pipe
    at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
    at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
    at sun.nio.ch.IOUtil.write(IOUtil.java:51)
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466)
    at org.mortbay.io.nio.ChannelEndPoint.flush(ChannelEndPoint.java:166)
    at org.mortbay.io.nio.SelectChannelEndPoint.flush(SelectChannelEndPoint.java:208)
    at org.mortbay.jetty.HttpGenerator.flush(HttpGenerator.java:693)
    ... 71 more

[2016-02-21 12:54:38,460] INFO StreamController - Got HTTP range: 3145728-6919999
[2016-02-21 12:54:38,458] ERROR JAXBWriter - Failed to marshal JAXB
java.lang.IllegalStateException: STREAM
    at org.mortbay.jetty.Response.getWriter(Response.java:583)
    at net.sourceforge.subsonic.controller.JAXBWriter.writeResponse(JAXBWriter.java:140)
    at net.sourceforge.subsonic.controller.JAXBWriter.writeErrorResponse(JAXBWriter.java:154)
    at net.sourceforge.subsonic.filter.RESTFilter.handleException(RESTFilter.java:76)
    at net.sourceforge.subsonic.filter.RESTFilter.doFilter(RESTFilter.java:62)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084)
    at net.sourceforge.subsonic.filter.ParameterDecodingFilter.doFilter(ParameterDecodingFilter.java:54)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084)
    at net.sourceforge.subsonic.filter.BootstrapVerificationFilter.doFilter(BootstrapVerificationFilter.java:59)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:360)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:712)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:405)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:139)
    at org.mortbay.jetty.Server.handle(Server.java:313)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:506)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:830)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:514)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:211)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:381)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:396)
    at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:442)

[2016-02-21 12:54:38,463] INFO PlayQueueInputStream - ivan listening to "Ottmar Liebert - Up Close [FLAC24-96khz]/6-Silence Excerpt.flac"
[2016-02-21 12:54:38,462] ERROR RESTFilter - Failed to write error response.
java.lang.IllegalStateException: STREAM
    at org.mortbay.jetty.Response.getWriter(Response.java:583)
    at net.sourceforge.subsonic.controller.JAXBWriter.writeResponse(JAXBWriter.java:140)
    at net.sourceforge.subsonic.controller.JAXBWriter.writeErrorResponse(JAXBWriter.java:154)
    at net.sourceforge.subsonic.filter.RESTFilter.handleException(RESTFilter.java:76)
    at net.sourceforge.subsonic.filter.RESTFilter.doFilter(RESTFilter.java:62)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084)
    at net.sourceforge.subsonic.filter.ParameterDecodingFilter.doFilter(ParameterDecodingFilter.java:54)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084)
    at net.sourceforge.subsonic.filter.BootstrapVerificationFilter.doFilter(BootstrapVerificationFilter.java:59)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:360)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:712)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:405)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:139)
    at org.mortbay.jetty.Server.handle(Server.java:313)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:506)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:830)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:514)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:211)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:381)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:396)
    at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:442)

[2016-02-21 12:54:38,480] INFO TranscodeInputStream - Starting transcoder: [/var/subsonic/transcode/ffmpeg] [-i] [/media/5225f81e-1aa4-410a-ad65-c0761722da69/Nas/Music/Ottmar Liebert - Up Close [FLAC24-96khz]/6-Silence Excerpt.flac] [-map] [0:0] [-b:a] [320k] [-v] [0] [-f] [mp3] [-]
[2016-02-21 12:54:38,695] INFO InputStreamReaderThread - (/var/subsonic/transcode/ffmpeg) Stream mapping:
[2016-02-21 12:54:38,696] INFO InputStreamReaderThread - (/var/subsonic/transcode/ffmpeg)   Stream #0.0 -> #0.0
[2016-02-21 12:54:38,697] INFO InputStreamReaderThread - (/var/subsonic/transcode/ffmpeg) Press ctrl-c to stop encoding
[2016-02-21 12:54:38,697] INFO InputStreamReaderThread - (/var/subsonic/transcode/ffmpeg) Warning, using s16 intermediate sample format for resampling
[2016-02-21 12:54:39,271] INFO InputStreamReaderThread - (/var/subsonic/transcode/ffmpeg) size=      43kB time=1.82 bitrate= 194.1kbits/s`

**I'm a dev so can help with fixing, just point me to the right direction.**

P.S. Thanks for a great app!

**Comment by dough10** [comment]
Thanks for bringing this to my attention. i will look into it more this morning and see what i can find out. It looks from the request you posted that you are using version 5.3 of Subsonic. Are you using the default transcoding settings? (transcoding to mp3)


 In just a few seconds of quick googling it looks like the client error is caused by the 'content-length' header not matching the 'content-range' header. I was able to find some posts on a similar issues  [http://stackoverflow.com/questions/24434231/err-content-length-mismatch-when-loading-audio](url) [https://bugs.chromium.org/p/chromium/issues/detail?id=161713](url) 
I am not going to say this is fully a Subsonic issue ATM but I am thinking it may be a issue between Chrome & Subsonic where Chrome is download just barely before the buffer and the server will timeout the connection from spending to much time idle. I will pass this to Sindre on the API forum and see what kind of response i get from him on the subject.

**Comment by IvanVas** [comment]
Yes, transcoding to mp3.
Thanks!

Btw, tested same scenario on jamstash, works there. Looks like it streams the whole song in one range there.

**Comment by IvanVas** [comment]
So there's a reason why it works in jamstash. It's max bitrate of 192kB/s. Works fine when I set the same in PolySonic

**Comment by dough10** [comment]
did jamstash have the same issue if set to 320kbps?

**Comment by IvanVas** [comment]
To best of my knowledge, it has no such option.

**Comment by dough10** [comment]
Oh lol sad how little i know about other Subsonic clients. You might also try "Subfire"  [http://p.subfireplayer.net/](url) and see if you have similar results there. It also uses the HTML5 audio element

**Comment by IvanVas** [comment]
Tried to debug with no luck, it's stuck and after a long pause jumps to buffering() function

**Comment by dough10** [comment]
I am not sure where to tell you to start looking to debug this.  It seems bandwidth related from what I can tell.  If you want to make a temp account for me to test with I would be glad to see what I can figure out.  You could email it to me @ Doughten.jimi@gmail.com

**Comment by IvanVas** [comment]
Updated to the latest libs and subsonic 6 on the Raspberry PI server. The problem remains.
I sent you the demo account, thanks

**Comment by dough10** [comment]
I get the same behavior (Content Length Mismatch) by coping a stream url into a Chrome tab but it doesn't seem to happen in Edge. Re downloading Firefox to test if it is only a chrome thing.

I will keep looking into the situation but there doesn't seem to be anything I can do in the code to fix the issue ATM.

**Comment by IvanVas** [comment]
Resolved by OS (raspbian) and subsonic reinstall.
